<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DistrictsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('districts')->insert([
            [
                'province_id' => 1,
                'name' => 'Colombo',
                'about' => 'The commercial capital of Sri Lanka.',
                'mostly_popular' => 'Arts & culture, Family friendly',
                'location' => '6.9271° N, 79.8612° E',
                'image' => '/img/colombo.webp',
                'travel_season' => 'December to March',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "province_id"=> 1,
                "name"=> "Gampaha",
                "about"=> "A rapidly developing district with urban and rural charm.",
                "mostly_popular"=> "Shopping, Nature parks",
                "location"=> "7.0840° N, 80.0098° E",
                "image"=> "uploads/img/gampaha.JPG",
                "travel_season"=> "December to March",
                'created_at' => now(),
                'updated_at' => now(),
            ],


            [
                'province_id' => 1,
                'name' => 'Kalutara',
                'about' => 'A coastal district known for beaches and historical sites.',
                'mostly_popular' => 'Beaches, Temples',
                'location' => '6.5854° N, 79.9607° E',
                'image' => 'uploads/img/kalutara.jpeg',
                'travel_season' => 'November to April',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'province_id' => 2,
                'name' => 'Kandy',
                'about' => 'The hill capital and cultural heart of Sri Lanka.',
                'mostly_popular' => 'Temple of the Tooth, Cultural shows',
                'location' => '7.2906° N, 80.6337° E',
                'image' => 'uploads/img/kandy.jpg',
                'travel_season' => 'December to April',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'province_id' => 2,
                'name' => 'Matale',
                'about' => 'Famous for spice gardens and Knuckles Mountain Range.',
                'mostly_popular' => 'Spice tours, Hiking',
                'location' => '7.4675° N, 80.6234° E',
                'image' => 'uploads/img/matale.jpg',
                'travel_season' => 'December to March',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'province_id' => 2,
                'name' => 'Nuwara Eliya',
                'about' => 'Known as Little England with tea plantations and cool climate.',
                'mostly_popular' => 'Tea estates, Gregory Lake',
                'location' => '6.9497° N, 80.7891° E',
                'image' => 'uploads/img/nuwaraeliya.webp',
                'travel_season' => 'February to April',
                'created_at' => now(),
                'updated_at' => now(),
            ],
           [
                'province_id' => 3,
                'name' => 'Galle',
                'about' => 'A coastal city with a Dutch colonial fort.',
                'mostly_popular' => 'Galle Fort, Beaches',
                'location' => '6.0329° N, 80.2170° E',
                'image' => 'uploads/img/galle.jpeg',
                'travel_season' => 'November to April',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'province_id' => 3,
                'name' => 'Matara',
                'about' => 'Historic city with fortifications and southern beaches.',
                'mostly_popular' => 'Surfing, Temples',
                'location' => '5.9549° N, 80.5550° E',
                'image' => 'uploads/img/matara.jpg',
                'travel_season' => 'November to April',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'province_id' => 3,
                'name' => 'Hambantota',
                'about' => 'A dry-zone district with wildlife and safari parks.',
                'mostly_popular' => 'Yala Safari, Beaches',
                'location' => '6.1246° N, 81.1185° E',
                'image' => 'uploads/img/hambantota.jpeg',
                'travel_season' => 'February to July',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'province_id' => 4,
                'name' => 'Jaffna',
                'about' => 'Cultural capital of Northern Sri Lanka.',
                'mostly_popular' => 'Jaffna Fort, Hindu temples',
                'location' => '9.6615° N, 80.0255° E',
                'image' => 'uploads/img/jafna.webp',
                'travel_season' => 'January to September',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'province_id' => 4,
                'name' => 'Kilinochchi',
                'about' => 'An agricultural hub in the Northern Province.',
                'mostly_popular' => 'Agriculture, Local culture',
                'location' => '9.3890° N, 80.3992° E',
                'image' => 'uploads/img/kilinochchi.jpg',
                'travel_season' => 'May to September',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'province_id' => 4,
                'name' => 'Mannar',
                'about' => 'Known for baobab trees, birds, and churches.',
                'mostly_popular' => 'Birdwatching, Beaches',
                'location' => '8.9800° N, 79.9044° E',
                'image' => 'uploads/img/mannar.jpg',
                'travel_season' => 'December to March',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'province_id' => 4,
                'name' => 'Mullaitivu',
                'about' => 'A coastal district with lagoons and fishing villages.',
                'mostly_popular' => 'Fishing, Lagoons',
                'location' => '9.2671° N, 80.8140° E',
                'image' => 'uploads/img/mullaitivu.jpg',
                'travel_season' => 'May to September',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'province_id' => 4,
                'name' => 'Vavuniya',
                'about' => 'A gateway town to the Northern Province.',
                'mostly_popular' => 'Archaeology, Local culture',
                'location' => '8.7542° N, 80.4980° E',
                'image' => 'uploads/img/vavuniya4.jpg',
                'travel_season' => 'January to March',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'province_id' => 5,
                'name' => 'Trincomalee',
                'about' => 'A port city with beautiful beaches and naval history.',
                'mostly_popular' => 'Nilaveli Beach, Koneswaram Temple',
                'location' => '8.5710° N, 81.2335° E',
                'image' => 'uploads/img/Trincomalee.webp',
                'travel_season' => 'May to September',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'province_id' => 5,
                'name' => 'Batticaloa',
                'about' => 'Known for lagoons, beaches, and musical fish.',
                'mostly_popular' => 'Beaches, Lagoons',
                'location' => '7.7170° N, 81.7006° E',
                'image' => 'uploads/img/Batticaloa.jpg',
                'travel_season' => 'May to September',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'province_id' => 5,
                'name' => 'Ampara',
                'about' => 'Rich in wildlife and farming lands.',
                'mostly_popular' => 'Arugam Bay, Wildlife parks',
                'location' => '7.2916° N, 81.6724° E',
                'image' => 'uploads/img/ampara.jpg',
                'travel_season' => 'April to September',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'province_id' => 6,
                'name' => 'Kurunegala',
                'about' => 'A central city surrounded by rock formations.',
                'mostly_popular' => 'Hiking, Historical sites',
                'location' => '7.4863° N, 80.3623° E',
                'image' => 'uploads/img/kurunegala.jpg',
                'travel_season' => 'January to March',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'province_id' => 6,
                'name' => 'Puttalam',
                'about' => 'Known for salt production, lagoons, and Wilpattu Park.',
                'mostly_popular' => 'Wilpattu Safari, Lagoons',
                'location' => '8.0362° N, 79.8283° E',
                'image' => 'uploads/img/puththalam.jpg',
                'travel_season' => 'January to March',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'province_id' => 7,
                'name' => 'Anuradhapura',
                'about' => 'An ancient capital with UNESCO World Heritage sites.',
                'mostly_popular' => 'Sacred City, Stupas',
                'location' => '8.3114° N, 80.4037° E',
                'image' => 'uploads/img/anuradhapura1.webp',
                'travel_season' => 'May to September',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'province_id' => 7,
                'name' => 'Polonnaruwa',
                'about' => 'Second ancient capital of Sri Lanka with ruins and reservoirs.',
                'mostly_popular' => 'Ruins, Safari',
                'location' => '7.9396° N, 81.0003° E',
                'image' => 'uploads/img/polonnaruwa.webp',
                'travel_season' => 'May to September',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'province_id' => 8,
                'name' => 'Badulla',
                'about' => 'A mountain district with waterfalls and tea estates.',
                'mostly_popular' => 'Ella, Demodara Bridge',
                'location' => '6.9934° N, 81.0550° E',
                'image' => 'uploads/img/adulla.jpg',
                'travel_season' => 'February to April',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'province_id' => 8,
                'name' => 'Monaragala',
                'about' => 'A rural district with forests and natural reserves.',
                'mostly_popular' => 'Hiking, Eco-tourism',
                'location' => '6.8726° N, 81.3494° E',
                'image' => 'uploads/img/monaragala.jpg',
                'travel_season' => 'May to September',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'province_id' => 9,
                'name' => 'Ratnapura',
                'about' => 'Gem capital of Sri Lanka surrounded by rainforests.',
                'mostly_popular' => 'Gems, Waterfalls',
                'location' => '6.6828° N, 80.3997° E',
                'image' => 'uploads/img/ratnapura.webp',
                'travel_season' => 'December to March',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'province_id' => 9,
                'name' => 'Kegalle',
                'about' => 'Known for elephant orphanage and rubber plantations.',
                'mostly_popular' => 'Pinnawala Orphanage, Nature',
                'location' => '7.2513° N, 80.3464° E',
                'image' => 'uploads/img/kegalle.webp',
                'travel_season' => 'January to March',
                'created_at' => now(),
                'updated_at' => now(),
            ],
                ]);
            }
        }
